In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [123]:
widthSize = plt.imread("Train/1.jpg").ravel()
x_tilda = np.zeros((2400,widthSize.size+1))
for i in range(0,2400):
    number =i+1
    img = plt.imread("Train/"+str(number)+".jpg").ravel()
    x_tilda[i][img.size]=1
    for j in range(0,img.size):
          x_tilda[i][j]=img[j]  
x_tilda_transpose = np.transpose(x_tilda)
x_tilda_transpose_x_tilda = np.dot(x_tilda_transpose,x_tilda)
inv_xt_x = np.linalg.pinv(x_tilda_transpose_x_tilda)
a=np.dot(inv_xt_x,x_tilda_transpose)
t0 = np.zeros((2400,1))
t1 = np.zeros((2400,1))
t2 = np.zeros((2400,1))
t3 = np.zeros((2400,1))
t4 = np.zeros((2400,1))
t5 = np.zeros((2400,1))
t6 = np.zeros((2400,1))
t7 = np.zeros((2400,1))
t8 = np.zeros((2400,1))
t9 = np.zeros((2400,1))
f = open("Train/Training Labels.txt", "r")
for i in range(0,2400):
    t_val=int(f.readline())
    if(t_val==0):
        t0[i][0]=1
    if(t_val==1):
        t1[i][0]=1
    if(t_val==2):
        t2[i][0]=1
    if(t_val==3):
        t3[i][0]=1
    if(t_val==4):
        t4[i][0]=1
    if(t_val==5):
        t5[i][0]=1 
    if(t_val==6):
        t6[i][0]=1
    if(t_val==7):
        t7[i][0]=1
    if(t_val==8):
        t8[i][0]=1
    if(t_val==9):
        t9[i][0]=1
w_tilde_0= a.dot(t0) 
w_tilde_1= a.dot(t1)
w_tilde_2= a.dot(t2)
w_tilde_3= a.dot(t3)
w_tilde_4= a.dot(t4)
w_tilde_5= a.dot(t5)
w_tilde_6= a.dot(t6)
w_tilde_7= a.dot(t7)
w_tilde_8= a.dot(t8)
w_tilde_9= a.dot(t9)
#print (w_tilde_9)
test = open("Test/Test Labels.txt", "r")
confusion_matrix = np.zeros((11,11))    
for i in range(1,11):
    confusion_matrix[0][i]=i-1#cols
    confusion_matrix[i][0]=i-1#cols
for i in range(0,200):
    number = i+1
    img = plt.imread("Test/"+str(number)+".jpg").ravel() 
    new_w_tilde_0 = (w_tilde_0[:-1]).ravel()
    answer0= np.dot(new_w_tilde_0,img)+w_tilde_0[w_tilde_0.size-1][0]
    result =answer0
    index=0
    new_w_tilde_1 = (w_tilde_1[:-1]).ravel()
    answer1= np.dot(new_w_tilde_1,img)+w_tilde_1[w_tilde_1.size-1][0]
    if (answer1>result):
        result =answer1
        index=1
    new_w_tilde_2 = (w_tilde_2[:-1]).ravel()
    answer2= np.dot(new_w_tilde_2,img)+w_tilde_2[w_tilde_2.size-1][0]
    if (answer2>result):
        result =answer2
        index=2
    new_w_tilde_3 = (w_tilde_3[:-1]).ravel()
    answer3= np.dot( new_w_tilde_3,img)+w_tilde_3[w_tilde_3.size-1][0]
    if (answer3>result):
        result =answer3
        index=3
    new_w_tilde_4 = (w_tilde_4[:-1]).ravel()
    answer4= np.dot( new_w_tilde_4,img)+w_tilde_4[w_tilde_4.size-1][0]
    if (answer4>result):
        result =answer4
        index=4
    new_w_tilde_5 = (w_tilde_5[:-1]).ravel()
    answer5= np.dot( new_w_tilde_5, img)+w_tilde_5[w_tilde_5.size-1][0]
    if (answer5>result):
        result =answer5
        index=5
    new_w_tilde_6 = (w_tilde_6[:-1]).ravel()
    answer6= np.dot(new_w_tilde_6,img)+w_tilde_6[w_tilde_6.size-1][0]
    if (answer6>result):
        result =answer6
        index=6
    new_w_tilde_7 = (w_tilde_7[:-1]).ravel()
    answer7= np.dot(new_w_tilde_7,img)+w_tilde_7[w_tilde_7.size-1][0]
    if (answer7>result):
        result =answer7
        index=7
    new_w_tilde_8 = (w_tilde_8[:-1]).ravel()
    answer8= np.dot(new_w_tilde_8,img)+w_tilde_8[w_tilde_8.size-1][0]
    if (answer8>result):
        result =answer8
        index=8
    new_w_tilde_9 = (w_tilde_9[:-1]).ravel()
    answer9= np.dot(new_w_tilde_9,img)+w_tilde_9[w_tilde_9.size-1][0]
    if (answer9>result):
        result =answer9
        index=9
    actual= int (test.readline())
    confusion_matrix[index+1][actual+1]=confusion_matrix[index+1][actual+1]+1
print (confusion_matrix)
# plt.matshow(confusion_matrix,fignum=None)
# plt.colorbar()
# plt.ylabel('Actual')
# plt.xlabel('Predicated')
# plt.savefig('Confusion.jpg')

[[ 0.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0. 19.  0.  1.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0. 20.  3.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  0.  0. 11.  0.  0.  0.  0.  1.  1.  0.]
 [ 3.  0.  0.  2. 17.  0.  1.  0.  1.  0.  1.]
 [ 4.  0.  0.  2.  0. 17.  0.  0.  0.  0.  1.]
 [ 5.  0.  0.  1.  1.  1. 14.  0.  0.  3.  1.]
 [ 6.  1.  0.  0.  0.  0.  1. 20.  0.  0.  0.]
 [ 7.  0.  0.  0.  0.  1.  0.  0. 15.  0.  4.]
 [ 8.  0.  0.  0.  2.  0.  2.  0.  0. 15.  0.]
 [ 9.  0.  0.  0.  0.  1.  2.  0.  3.  1. 12.]]
